import { jsPDF } from 'jspdf';

/**
 * Escapes CSV field value
 * @param {string|number} value
 * @returns {string}
 */
function escapeCsv(value) {
  if (value === null || value === undefined) return '';
  const stringVal = String(value);
  if (stringVal.includes(',') || stringVal.includes('"') || stringVal.includes('\n')) {
    return `"${stringVal.replace(/"/g, '""')}"`;
  }
  return stringVal;
}

/**
 * Builds and returns a formatted jsPDF document instance for a logged report
 * containing executive summary and applied multi-dimensional filters
 * @param {Object} log
 * @returns {jsPDF}
 */
export function buildAuditPdfReport(log) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();

  // Header brand banner
  doc.setFillColor(6, 95, 70); // #065f46 — Forest Emerald
  doc.rect(0, 0, pageWidth, 28, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('SMART WILDLIFE CONSERVATION SYSTEM', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Conservation Analytics & Audit Trail Record Summary', 14, 19);

  // Metadata block
  doc.setTextColor(40, 40, 40);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('REPORT AUDIT METADATA', 14, 38);
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 40, pageWidth - 14, 40);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report ID: ${log.reportId || 'REP-GEN'}`, 14, 47);
  doc.text(`Report Type: ${log.reportType?.replace(/_/g, ' ') || 'INCIDENT ANALYSIS'}`, 14, 53);
  doc.text(`Status: ${log.status || 'SUCCESS'}`, 14, 59);

  doc.text(`Generated By: ${log.userName || log.userId || 'Park Manager'}`, 110, 47);
  doc.text(`Timestamp: ${new Date(log.timestamp).toLocaleString()}`, 110, 53);
  doc.text(`Processed Records: ${log.recordCount ?? 0}`, 110, 59);

  // Executive Telemetry Summary
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  doc.text('EXECUTIVE TELEMETRY SUMMARY', 14, 72);
  doc.line(14, 74, pageWidth - 14, 74);

  const boxWidth = (pageWidth - 28 - 9) / 4;
  const metrics = [
    { label: 'RECORD COUNT', val: String(log.recordCount ?? 0) },
    { label: 'AUDIT STATUS', val: String(log.status || 'SUCCESS') },
    { label: 'EXECUTION TYPE', val: String(log.reportType?.slice(0, 10) || 'REPORT') },
    { label: 'SECURITY ROLE', val: 'PARK MGR' },
  ];

  metrics.forEach((m, idx) => {
    const x = 14 + idx * (boxWidth + 3);
    doc.setFillColor(245, 245, 244);
    doc.roundedRect(x, 79, boxWidth, 18, 2, 2, 'F');
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'bold');
    doc.text(m.label, x + 3, 85);
    doc.setTextColor(6, 95, 70);
    doc.setFontSize(11);
    doc.text(m.val, x + 3, 93);
  });

  // Applied Report Filters & Query Criteria Section
  let currentY = 110;
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(40, 40, 40);
  doc.text('APPLIED QUERY CRITERIA & MULTI-DIMENSIONAL FILTERS', 14, currentY);
  doc.line(14, currentY + 2, pageWidth - 14, currentY + 2);
  currentY += 8;

  const criteria = log.criteria || {};
  const filterRows = [
    ['Conservation Park', criteria.park || 'ALL'],
    ['Start Date', criteria.dateFrom || 'N/A'],
    ['End Date', criteria.dateTo || 'N/A'],
    ['Incident Type', criteria.incidentType || 'ALL'],
    ['Severity Threshold', criteria.severity || 'ALL'],
    ['Target Species', criteria.species || 'ALL'],
    ['Location / Sector', criteria.zone || 'ALL'],
  ];

  // Table header
  doc.setFillColor(240, 240, 240);
  doc.rect(14, currentY, pageWidth - 28, 7, 'F');
  doc.setFontSize(8.5);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(70, 70, 70);
  doc.text('FILTER PARAMETER', 18, currentY + 5);
  doc.text('APPLIED VALUE', 100, currentY + 5);
  currentY += 8;

  // Table rows
  doc.setFont('helvetica', 'normal');
  filterRows.forEach(([param, val], idx) => {
    if (idx % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(14, currentY - 1, pageWidth - 28, 7, 'F');
    }
    doc.setTextColor(80, 80, 80);
    doc.setFont('helvetica', 'bold');
    doc.text(param, 18, currentY + 4);

    doc.setTextColor(20, 20, 20);
    doc.setFont('helvetica', 'normal');
    doc.text(String(val), 100, currentY + 4);
    currentY += 7.5;
  });

  // Verification & Signoff Box
  currentY += 8;
  doc.setFillColor(240, 253, 244);
  doc.roundedRect(14, currentY, pageWidth - 28, 24, 2, 2, 'F');
  doc.setDrawColor(187, 247, 208);
  doc.roundedRect(14, currentY, pageWidth - 28, 24, 2, 2, 'S');

  doc.setTextColor(6, 95, 70);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9.5);
  doc.text('REGULATORY COMPLIANCE & IMMUTABLE AUDIT CERTIFICATION', 18, currentY + 7);

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(50, 50, 50);
  doc.text(
    'This document certifies the immutable query parameters and regulatory summary captured',
    18,
    currentY + 13
  );
  doc.text(
    'within the Smart Wildlife Conservation System Audit Trail Matrix for evidence-based governance.',
    18,
    currentY + 18
  );

  // Page Footer
  doc.setDrawColor(220, 220, 220);
  doc.line(14, 275, pageWidth - 14, 275);
  doc.setFontSize(7.5);
  doc.setTextColor(120, 120, 120);
  doc.text(`Official WildGuard Audit Log Export • Document ID: ${log.reportId || 'AUDIT'}`, 14, 281);
  doc.text(`Exported: ${new Date().toLocaleString()}`, 130, 281);

  return doc;
}

/**
 * Builds structured CSV content string for a logged report
 * @param {Object} log
 * @returns {string}
 */
export function buildAuditCsvReport(log) {
  const criteria = log.criteria || {};
  const rows = [];

  // Report Header Section
  rows.push(['WILDGUARD CONSERVATION SYSTEM - SYSTEM AUDIT TRAIL RECORD']);
  rows.push(['Report ID', escapeCsv(log.reportId || 'REP-GEN')]);
  rows.push(['Report Type', escapeCsv(log.reportType || 'INCIDENT_ANALYSIS')]);
  rows.push(['Execution Status', escapeCsv(log.status || 'SUCCESS')]);
  rows.push(['Generated By', escapeCsv(log.userName || log.userId || 'Park Manager')]);
  rows.push(['Logged Timestamp', escapeCsv(new Date(log.timestamp).toLocaleString())]);
  rows.push(['Processed Records Count', log.recordCount ?? 0]);
  rows.push([]);

  // Executive Metrics Summary Section
  rows.push(['EXECUTIVE AUDIT SUMMARY']);
  rows.push(['Metric', 'Value']);
  rows.push(['Record Count', log.recordCount ?? 0]);
  rows.push(['Audit Status', escapeCsv(log.status || 'SUCCESS')]);
  rows.push(['Execution Type', escapeCsv(log.reportType || 'REPORT')]);
  rows.push(['Exported At', escapeCsv(new Date().toISOString())]);
  rows.push([]);

  // Applied Multi-Dimensional Filters Section
  rows.push(['APPLIED QUERY CRITERIA & MULTI-DIMENSIONAL FILTERS']);
  rows.push(['Filter Parameter', 'Applied Value']);
  rows.push(['Conservation Park', escapeCsv(criteria.park || 'ALL')]);
  rows.push(['Start Date', escapeCsv(criteria.dateFrom || 'N/A')]);
  rows.push(['End Date', escapeCsv(criteria.dateTo || 'N/A')]);
  rows.push(['Incident Type', escapeCsv(criteria.incidentType || 'ALL')]);
  rows.push(['Severity Threshold', escapeCsv(criteria.severity || 'ALL')]);
  rows.push(['Target Species', escapeCsv(criteria.species || 'ALL')]);
  rows.push(['Location / Sector', escapeCsv(criteria.zone || 'ALL')]);

  return rows.map((r) => r.join(',')).join('\n');
}

/**
 * Triggers PDF download for a logged report
 * @param {Object} log
 */
export function downloadAuditPdf(log) {
  const doc = buildAuditPdfReport(log);
  const filename = `audit_report_${log.reportId || 'record'}_${Date.now()}.pdf`;
  doc.save(filename);
  return filename;
}

/**
 * Triggers CSV download for a logged report
 * @param {Object} log
 */
export function downloadAuditCsv(log) {
  const csvContent = buildAuditCsvReport(log);
  const filename = `audit_report_${log.reportId || 'record'}_${Date.now()}.csv`;
  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  return filename;
}
